name: ids_driver
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1
  firebase_storage: ^11.0.4
  cloud_firestore: ^4.0.4
  firebase_messaging: ^14.2.5
  flutter_local_notifications: ^13.0.0
  http: ^0.13.5
  intl: ^0.17.0
  # toggle_switch: ^2.0.1
  camera: ^0.10.0+4
  path_provider: ^2.0.11
  android_path_provider: ^0.3.0
  camera_web: ^0.3.0+1
  slider_button: ^2.0.0
  toggle_switch: ^2.0.1
  uuid: ^3.0.7
  flutter_secure_storage: ^8.0.0
  # device_information: ^0.0.4
  # platform_device_id: ^1.0.1
  # device_info_plus: ^9.0.1
  # unique_identifier: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
    - assets/icons/
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages